apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: starlight-spell-checker
  namespace: starlight-spell-checker
spec:
  secretName: starlight-spell-checker
  issuerRef:
    name: acme-issuer
    kind: ClusterIssuer
  dnsNames:
    - "starlight-spell-checker.trueberryless.org"
